dist: xenial

language: python

python:
  - "3.7"

cache: pip

install:
  - pip install -U bdrk flask lightgbm pylint pyspark scikit-learn

branches:
  only:
    - master
    - http_serve

script:
  - pylint *.py
