sudo: required

dist: xenial

language: python

python:
  - "3.7"

cache: pip

install:
  - pip install -U pylint pyspark pandas lightgbm bedrock-cli grpcio-tools grpcio protobuf jinja2 werkzeug apache-airflow

branches:
  only:
    - master

script:
  - python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. protos/serve.proto
  - pylint --disable=duplicate-code --ignore=serve_pb2.py,serve_pb2_grpc.py *.py
