sudo: required

dist: xenial

language: python

python:
  - "3.7"

cache: pip

install:
  - pip install -U pylint pyspark pandas lightgbm bdrk grpcio-tools grpcio protobuf jinja2 werkzeug apache-airflow

branches:
  only:
    - master
    - http_serve

script:
  - pylint --disable=duplicate-code --ignore=serve_pb2.py,serve_pb2_grpc.py *.py
